export const D = {
  bg:           "#F7F6F2",
  surface:      "#FFFFFF",
  card:         "#FFFFFF",

  heroA:        "#1C1C2E",
  heroB:        "#2D2B55",
  heroAccent:   "#6C63FF",
  heroGlow:     "#A78BFA",

  ink:          "#111118",
  inkMid:       "#3D3C52",
  inkSoft:      "#8B8AA5",
  inkGhost:     "#C4C3D0",

  emerald:      "#00B37D",
  emeraldBg:    "#E6FAF4",
  rose:         "#F04E6A",
  roseBg:       "#FEE9ED",
  amber:        "#F59E0B",
  amberBg:      "#FEF3C7",
  blue:         "#3B82F6",
  blueBg:       "#EFF6FF",
  violet:       "#8B5CF6",
  violetBg:     "#F5F3FF",
  orange:       "#F97316",
  orangeBg:     "#FFF3E8",
  teal:         "#14B8A6",
  tealBg:       "#F0FDFA",

  border:       "#ECEAE4",
  borderStrong: "#D9D6CC",
  borderFocus:  "#C4B5FD",
  shadow:       "rgba(17,17,24,0.06)",
};
